/**
 * 渠道 → Gingiris Skill 映射
 * skillIds 数组按优先级排列，Agent 注入时会合并全部 SKILL.md 原文
 */
export interface ChannelDefinition {
  channelId: string;
  skillIds: string[];
  name: string;
  nameEn: string;
  description: string;
  medium: 'community' | 'social_text' | 'owned' | 'video' | 'visual' | 'research' | 'operations';
  outputMode: 'publish_ready_text' | 'production_package' | 'operational_plan';
  deliverables: string[];
  locales: string[];
  tier: 'mvp' | 'p1' | 'p2' | 'extended' | 'phase0';
  postsPerWeek: number;
  campaignDays: number;
  defaultTaskTypes: string[];
}

/**
 * Every channel worker receives the same compact evidence and voice contracts.
 * Platform playbooks remain channel-specific and are appended after these.
 */
export const CHANNEL_SHARED_SKILL_IDS = [
  'custom/research-grounded-writing',
  'custom/authentic-editorial-voice',
  'custom/creative-atom-repurposing',
] as const;

export function getResolvedChannelSkillIds(def: ChannelDefinition): string[] {
  return [...new Set([...CHANNEL_SHARED_SKILL_IDS, ...def.skillIds])];
}

export const CHANNEL_DEFINITIONS: ChannelDefinition[] = [
  {
    channelId: 'xiaohongshu',
    skillIds: ['custom/xiaohongshu'],
    name: '小红书',
    nameEn: 'Xiaohongshu',
    description: '公域种草 + 故事化内容，适合工具/课程/咨询类 side project 冷启动',
    medium: 'visual',
    outputMode: 'production_package',
    deliverables: ['图文笔记', '故事脚本', '封面与配图 brief'],
    locales: ['zh'],
    tier: 'mvp',
    postsPerWeek: 3,
    campaignDays: 30,
    defaultTaskTypes: ['post', 'story', 'reply'],
  },
  {
    channelId: 'user_outreach',
    skillIds: ['gingiris-kol-outreach', 'kol-outreach'],
    name: '私域 / 朋友圈',
    nameEn: 'Private Outreach',
    description: '朋友圈信任建设 + 精准私信触达，转化路径最短的渠道',
    medium: 'social_text',
    outputMode: 'publish_ready_text',
    deliverables: ['朋友圈文案', '私信', '跟进话术'],
    locales: ['zh', 'en'],
    tier: 'mvp',
    postsPerWeek: 2,
    campaignDays: 30,
    defaultTaskTypes: ['moments', 'dm', 'followup'],
  },
  {
    channelId: 'website_copy',
    skillIds: ['custom/website-conversion', 'gingiris-seo-geo-agent'],
    name: '官网 / 落地页',
    nameEn: 'Website Copy',
    description: 'Day1 落地页 Hero 优化，所有渠道流量的转化枢纽',
    medium: 'owned',
    outputMode: 'publish_ready_text',
    deliverables: ['落地页文案', '页面结构', '转化实验 brief'],
    locales: ['zh', 'en'],
    tier: 'mvp',
    postsPerWeek: 1,
    campaignDays: 30,
    defaultTaskTypes: ['prep', 'copy'],
  },
  {
    channelId: 'wechat_official',
    skillIds: ['custom/wechat-official'],
    name: '微信公众号',
    nameEn: 'WeChat Official',
    description: '长文深度内容，建立专业信任与搜索沉淀',
    medium: 'owned',
    outputMode: 'publish_ready_text',
    deliverables: ['深度文章', '标题与摘要', '配图 brief'],
    locales: ['zh'],
    tier: 'p1',
    postsPerWeek: 1,
    campaignDays: 30,
    defaultTaskTypes: ['article', 'post'],
  },
  {
    channelId: 'user_interview',
    skillIds: ['gingiris-user-interview'],
    name: '用户访谈',
    nameEn: 'User Interview',
    description: 'PMF 验证与用户发现，验证不足时的 Phase 0 核心',
    medium: 'research',
    outputMode: 'operational_plan',
    deliverables: ['访谈提纲', '招募话术', '洞察综合'],
    locales: ['zh', 'en'],
    tier: 'phase0',
    postsPerWeek: 2,
    campaignDays: 30,
    defaultTaskTypes: ['prep', 'interview', 'synthesis'],
  },
  {
    channelId: 'product_hunt',
    skillIds: ['product-hunt-playbook', 'gingiris-launch', 'product-hunt-launch-guide'],
    name: 'Product Hunt',
    nameEn: 'Product Hunt',
    description: '海外产品发布集中曝光节点，冲榜有完整 SOP',
    medium: 'community',
    outputMode: 'production_package',
    deliverables: ['tagline', '产品描述', 'Maker Comment', '发布素材 brief'],
    locales: ['en'],
    tier: 'p1',
    postsPerWeek: 1,
    campaignDays: 30,
    defaultTaskTypes: ['launch', 'maker_comment', 'post'],
  },
  {
    channelId: 'twitter_x',
    skillIds: ['gingiris-twitter-agent-ops'],
    name: 'Twitter / X',
    nameEn: 'Twitter / X',
    description: 'Build in public，海外 builder 社区主阵地',
    medium: 'social_text',
    outputMode: 'publish_ready_text',
    deliverables: ['短帖', 'Thread', '可粘贴的引用评论草稿'],
    locales: ['en'],
    tier: 'p1',
    postsPerWeek: 3,
    campaignDays: 30,
    defaultTaskTypes: ['thread', 'post', 'quote_reply'],
  },
  {
    channelId: 'linkedin',
    skillIds: ['custom/linkedin-organic', 'b2b-marketing-playbook'],
    name: 'LinkedIn',
    nameEn: 'LinkedIn',
    description: 'B2B 专业内容与决策者触达',
    medium: 'social_text',
    outputMode: 'publish_ready_text',
    deliverables: ['创始人帖子', '观点帖', '文档轮播文案'],
    locales: ['en', 'zh'],
    tier: 'p2',
    postsPerWeek: 2,
    campaignDays: 30,
    defaultTaskTypes: ['post', 'reply'],
  },
  {
    channelId: 'reddit',
    skillIds: ['custom/reddit-community'],
    name: 'Reddit',
    nameEn: 'Reddit',
    description: 'Reddit 营销与 AI 引用优化',
    medium: 'community',
    outputMode: 'publish_ready_text',
    deliverables: ['社区帖子草稿', '可粘贴的高质量回复'],
    locales: ['en'],
    tier: 'p1',
    postsPerWeek: 2,
    campaignDays: 30,
    defaultTaskTypes: ['post', 'reply'],
  },
  {
    channelId: 'hacker_news',
    skillIds: ['custom/hacker-news', 'external/blog-writing-guide'],
    name: 'Hacker News',
    nameEn: 'Hacker News',
    description: 'Show HN、技术深挖与工程师社区对话，以可验证细节和取舍而非营销话术取得信任',
    medium: 'community',
    outputMode: 'production_package',
    deliverables: ['Show HN 提交包', '技术文章草稿', '可粘贴的首条评论与回复预案'],
    locales: ['en'],
    tier: 'p1',
    postsPerWeek: 1,
    campaignDays: 30,
    defaultTaskTypes: ['show_hn', 'article', 'reply'],
  },
  {
    channelId: 'indie_hackers',
    skillIds: ['custom/indie-hackers', 'external/blog-writing-guide'],
    name: 'Indie Hackers',
    nameEn: 'Indie Hackers',
    description: '用真实决策、实验和复盘写出可发布的 builder 内容，建立信任而非投放式曝光',
    medium: 'community',
    outputMode: 'publish_ready_text',
    deliverables: ['创始人故事草稿', 'Build Log', '实验复盘帖', '反馈请求帖'],
    locales: ['en'],
    tier: 'p1',
    postsPerWeek: 1,
    campaignDays: 30,
    defaultTaskTypes: ['founder_story', 'build_log', 'experiment', 'post'],
  },
  {
    channelId: 'tiktok',
    skillIds: ['custom/short-video-script'],
    name: 'TikTok',
    nameEn: 'TikTok',
    description: '用原生竖屏短视频快速测试 Hook、产品演示和创始人表达',
    medium: 'video',
    outputMode: 'production_package',
    deliverables: ['口播稿', '分镜与镜头清单', '字幕与封面', 'Hook 测试'],
    locales: ['en', 'zh'],
    tier: 'p1',
    postsPerWeek: 3,
    campaignDays: 30,
    defaultTaskTypes: ['short_script', 'screen_demo', 'talking_head', 'review'],
  },
  {
    channelId: 'youtube',
    skillIds: ['custom/youtube-video', 'custom/short-video-script'],
    name: 'YouTube',
    nameEn: 'YouTube',
    description: '用 Shorts 获取发现，用长视频教程、演示和深度解释沉淀搜索与信任',
    medium: 'video',
    outputMode: 'production_package',
    deliverables: ['Shorts 制作包', '长视频脚本', '标题与缩略图概念', '章节与镜头表'],
    locales: ['en', 'zh'],
    tier: 'p1',
    postsPerWeek: 2,
    campaignDays: 30,
    defaultTaskTypes: ['short_script', 'long_video', 'tutorial', 'review'],
  },
  {
    channelId: 'instagram',
    skillIds: ['custom/instagram-visual', 'custom/short-video-script'],
    name: 'Instagram',
    nameEn: 'Instagram',
    description: '用 Carousel、Meme、Reels 和 Stories 把产品洞察变成可看、可存、可分享的视觉内容',
    medium: 'visual',
    outputMode: 'production_package',
    deliverables: ['轮播逐页文案', 'Meme 方案', 'Reels 脚本', 'Stories 序列与美术 brief'],
    locales: ['en', 'zh'],
    tier: 'p1',
    postsPerWeek: 2,
    campaignDays: 30,
    defaultTaskTypes: ['carousel', 'meme', 'reel_script', 'stories'],
  },
  {
    channelId: 'seo',
    skillIds: ['gingiris-seo-geo-agent', 'gr-blog-post', 'gr-backlinks'],
    name: 'SEO 内容',
    nameEn: 'SEO',
    description: '围绕用户问题建立可持续被搜索、引用和复用的内容集群',
    medium: 'owned',
    outputMode: 'publish_ready_text',
    deliverables: ['研究型文章', '页面优化', '内部链接 brief'],
    locales: ['en', 'zh'],
    tier: 'p1',
    postsPerWeek: 1,
    campaignDays: 30,
    defaultTaskTypes: ['research', 'article', 'optimize'],
  },
  {
    channelId: 'directory',
    skillIds: ['custom/directory-submission'],
    name: '产品目录',
    nameEn: 'Directories',
    description: '持续匹配、准备并提交产品目录，扩大产品被发现和引用的覆盖面',
    medium: 'operations',
    outputMode: 'operational_plan',
    deliverables: ['目录批次', '提交资料', '验证与复查'],
    locales: ['en', 'zh'],
    tier: 'p1',
    postsPerWeek: 2,
    campaignDays: 30,
    defaultTaskTypes: ['batch', 'verification', 'review'],
  },
  {
    channelId: 'github_growth',
    skillIds: ['gingiris-opensource', 'github-stars-playbook'],
    name: 'GitHub 增长',
    nameEn: 'GitHub Growth',
    description: '开源项目 GitHub Stars 增长系统',
    medium: 'community',
    outputMode: 'production_package',
    deliverables: ['README', 'Release Note', '仓库发布内容'],
    locales: ['en'],
    tier: 'extended',
    postsPerWeek: 2,
    campaignDays: 30,
    defaultTaskTypes: ['post', 'readme', 'release_note'],
  },
  {
    channelId: 'competitor_research',
    skillIds: ['competitor-research-playbook'],
    name: '竞品研究',
    nameEn: 'Competitor Research',
    description: '增长飞轮拆解与竞品传播链分析',
    medium: 'research',
    outputMode: 'operational_plan',
    deliverables: ['竞品证据', '传播链拆解', '机会假设'],
    locales: ['zh', 'en'],
    tier: 'phase0',
    postsPerWeek: 1,
    campaignDays: 30,
    defaultTaskTypes: ['prep', 'research'],
  },
];

export const CHANNEL_ROUTER_SKILL_IDS = ['gingiris-growth-finder', 'go-to-market-playbook'];

export const CHANNEL_RECOMMENDER_SKILL_IDS = [
  ...CHANNEL_ROUTER_SKILL_IDS,
  'custom/channel-recommender',
] as const;

export const KICKOFF_SKILL_IDS = ['go-to-market-playbook', 'startup-launch-playbook'];

export function getChannelDefinition(channelId: string): ChannelDefinition | undefined {
  return CHANNEL_DEFINITIONS.find((c) => c.channelId === channelId);
}
