'use client';

import { useEffect } from 'react';
import { useLocale } from 'next-intl';
import { Link } from '@/i18n/navigation';
import { useGtm } from '@/lib/gtm/store';
import { useViewContext } from '@/lib/gtm/view-context-provider';

export default function ReviewsPage() {
  const { store } = useGtm(); const isZh = useLocale() !== 'en'; const { setViewContext, clearViewContext } = useViewContext(); const launch = store.launch;
  useEffect(() => { if (!launch) return; setViewContext({ view: 'weekly_review', entityType: 'weekly_review_collection', entityId: launch.project.id, title: 'Weekly Reviews', revision: launch.weeklyReviews.reduce((sum, review) => sum + review.revision, 0) }); return clearViewContext; }, [clearViewContext, launch, setViewContext]);
  if (!launch) return <div className="flex h-full items-center justify-center"><Link href="/app" className="text-sm text-zinc-400">{isZh ? '先建立冷启动 →' : 'Build your launch first →'}</Link></div>;
  const currentWeek = Math.min(4, Math.ceil(launch.project.currentDay / 7));
  return <div className="mx-auto max-w-5xl px-4 py-7 sm:px-8 sm:py-10"><header><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-300">Campaign Learning Loop</p><h1 className="mt-2 text-3xl font-black tracking-tight text-white">Weekly Reviews</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">{isZh ? 'Review Agent 自动读取任务状态、发布 URL、公开互动、目录状态与用户反馈。合理调整默认应用到未来任务，不需要逐条审批。' : 'The Review Agent reads task outcomes, published URLs, public engagement, directory status, and feedback. Reasonable adjustments apply to future work automatically.'}</p></header><div className="mt-7 space-y-3">{launch.weeklyReviews.map((review) => { const due = launch.project.currentDay >= review.week * 7; const tasks = store.todos.filter((todo) => Math.ceil(todo.dayIndex / 7) === review.week); const done = tasks.filter((todo) => todo.status === 'done' || todo.publishedUrl).length; return <section key={review.id} className={`rounded-3xl border p-6 ${due ? 'border-emerald-400/20 bg-emerald-400/[0.03]' : review.week === currentWeek ? 'border-white/15 bg-white/[0.04]' : 'border-white/[0.07] bg-white/[0.02]'}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-[10px] uppercase tracking-[0.18em] text-zinc-600">Week {review.week} · Day {review.week * 7}</span><h2 className="mt-2 text-xl font-bold text-white">{launch.blueprint?.weeks[review.week - 1]?.objective}</h2></div><span className={`rounded-full px-3 py-1 text-[10px] uppercase ${due ? 'bg-emerald-400/10 text-emerald-300' : review.week === currentWeek ? 'bg-sky-400/10 text-sky-300' : 'bg-white/[0.04] text-zinc-600'}`}>{due ? (isZh ? '已到期，可复盘' : 'Due for review') : review.week === currentWeek ? (isZh ? '执行中' : 'In progress') : (isZh ? '未开始' : 'Upcoming')}</span></div><div className="mt-5 grid gap-2 sm:grid-cols-4">{[[isZh ? '任务' : 'Tasks', tasks.length], [isZh ? '完成' : 'Completed', done], [isZh ? '发布 URL' : 'Published URLs', tasks.filter((todo) => todo.publishedUrl).length], [isZh ? '跳过/失败' : 'Skipped / failed', tasks.filter((todo) => todo.status === 'skipped' || todo.launchStatus === 'failed').length]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-black/15 p-3"><span className="block text-[9px] uppercase tracking-[0.14em] text-zinc-600">{label}</span><strong className="mt-2 block text-lg text-white">{value}</strong></div>)}</div><p className="mt-4 text-xs leading-5 text-zinc-500">{review.summary}</p>{review.appliedChanges.length > 0 && <div className="mt-4 border-t border-white/[0.07] pt-4"><p className="text-[10px] uppercase tracking-[0.16em] text-zinc-600">Updated Next Week</p>{review.appliedChanges.map((change) => <p key={change} className="mt-2 text-xs text-zinc-400">✓ {change}</p>)}</div>}</section>; })}</div></div>;
}

