export const CONFIGURED_DIRECTORY_ADAPTERS: Record<string, string> = {
  'peerpush.net': 'peerpush',
  'openhunts.com': 'openhunts',
  'earlyhunt.com': 'earlyhunt',
  'hot100.ai': 'hot100',
  'uneed.best': 'uneed',
  'neeed.directory': 'neeed_directory',
  'foundrlist.com': 'foundrlist',
  'open-launch.com': 'open_launch',
  'futuretools.io': 'future_tools',
  'tools.launchllama.co': 'launchllama_tools',
  'rankinpublic.xyz': 'rank_in_public',
  'microsaasexamples.com': 'micro_saas_examples',
  'startups.fm': 'startups_fm',
  'buildvoyage.com': 'build_voyage',
  'madewithlovable.com': 'made_with_lovable',
  'llmrelevance.com': 'llm_relevance',
  'hunt0.com': 'hunt0',
  'saasgrow.app': 'saasgrow',
  'madewithbolt.com': 'made_with_bolt',
  'toolpilot.ai': 'toolpilot',
  'devhunt.org': 'devhunt',
  'alternativeto.net': 'alternative_to',
  'startupbase.io': 'startupbase',
  'sideprojectors.com': 'sideprojectors',
  'launchigniter.com': 'launch_igniter',
  'startupfa.st': 'startup_fast',
  'unitelist.com': 'unitelist',
  'fridayhunt.com': 'fridayhunt',
  'peerlist.io': 'peerlist',
  'superlaun.ch': 'super_launch',
  'tinylaunch.com': 'tinylaunch',
  'firsto.co': 'firsto',
  'auraplusplus.com': 'aura_plus_plus',
  'toolfio.com': 'toolfio',
  'twelve.tools': 'twelve_tools',
  'fazier.com': 'fazier',
  'dang.ai': 'dang_ai',
  'findly.tools': 'findly_tools',
  'betalist.com': 'betalist',
  'tinystartups.com': 'tiny_startups',
  'acidtools.com': 'acid_tools',
  'startupfa.me': 'startup_fame',
  'turbo0.com': 'turbo0',
  'aitools.inc': 'ai_tools_inc',
  'nxgntools.com': 'nxgn_tools',
  'indie.deals': 'indie_deals',
  'saashunt.best': 'saas_hunt_best',
  'appalist.com': 'appalist',
  'weliketools.com': 'weliketools',
  'startuptrusted.com': 'startup_trusted',
  'promoteproject.com': 'promote_project',
  'saasbison.com': 'saas_bison',
  'proofstories.io': 'proofstories',
  'findyoursaas.com': 'find_your_saas',
  'indiehub.best': 'indiehub',
  'dododirectory.com': 'dodo_directory',
  'sumodir.com': 'sumodir',
  'confettisaas.com': 'confetti_saas',
  'shipyardhq.dev': 'shipyard_hq',
  'resource.fyi': 'resource_fyi',
  'saashub.com': 'saashub',
  'microlaunch.net': 'microlaunch',
  'alternative.me': 'alternative_me',
  'toolfolio.io': 'toolfolio',
  'stellarlaunch.org': 'stellar_launch',
  'indiehackerstacks.com': 'indie_hacker_stacks',
  'productlaunchpad.app': 'product_launchpad',
  'launchy.tools': 'launchy',
  'sourceforge.net': 'sourceforge',
  'g2.com': 'g2',
  'producthunt.com': 'product_hunt',
  'capterra.com': 'capterra',
  'submitaitools.org': 'submit_ai_tools',
  'softwareworld.co': 'software_world',
  'startupstash.com': 'startup_stash',
  'magicbox.tools': 'magicbox_tools',
};

export const CONFIGURED_DIRECTORY_COUNT = Object.keys(
  CONFIGURED_DIRECTORY_ADAPTERS
).length;

export function directoryAdapterId(rawUrl: string): string | null {
  try {
    const hostname = new URL(rawUrl).hostname.replace(/^www\./, '');
    return CONFIGURED_DIRECTORY_ADAPTERS[hostname] ?? null;
  } catch {
    return null;
  }
}
