(function installNowBuildDirectoryCatalog(global) {
  const directories = [
    {
      id: 'uneed',
      name: 'Uneed',
      submitUrl: 'https://www.uneed.best/submit-a-tool',
      hosts: ['uneed.best'],
      pricing: 'Free + Paid',
      entryStage: 'url_preview',
      notes: '第一步无需账号；填写名称和网址后由平台抓取，再进入完整资料页。',
    },
    {
      id: 'peerpush',
      name: 'PeerPush',
      submitUrl: 'https://peerpush.com/submit',
      hosts: ['peerpush.com', 'peerpush.net'],
      pricing: 'Free + Paid',
      entryStage: 'full_form',
      notes: '优先使用 Google 登录；填写网址后调用站内 Autofill with AI，再补齐定价和缺失字段。',
    },
    {
      id: 'aura_plus_plus',
      name: 'Aura++',
      submitUrl: 'https://auraplusplus.com/projects/submit',
      hosts: ['auraplusplus.com'],
      pricing: 'Free + Paid',
      entryStage: 'wizard',
      notes: 'Google 登录已验证；五阶段为 Project Info、Details、Launch Date、Review、Backlink。第一阶段需要 200+ 词介绍、Logo 和 16:9 产品图。',
    },
    {
      id: 'openhunts',
      name: 'OpenHunts',
      submitUrl: 'https://openhunts.com/projects/submit',
      hosts: ['openhunts.com'],
      pricing: 'Free + Paid',
      entryStage: 'full_form',
      notes: '优先使用 Google 登录；填写网址后调用站内 Auto-fill，并补齐分类、定价、Logo 和产品截图。',
    },
    {
      id: 'toolfio',
      name: 'Toolfio',
      submitUrl: 'https://toolfio.com/submit',
      hosts: ['toolfio.com'],
      pricing: 'Free + Paid',
      entryStage: 'plan_gate',
      blocker: '免费方案要求站点达到平台条件并添加永久徽章；插件不会修改产品官网。',
      notes: '免费方案要求 DR 5+ 和永久徽章；插件停在方案页，不自动确认站外改动或触发付款。',
    },
    {
      id: 'earlyhunt',
      name: 'EarlyHunt',
      submitUrl: 'https://earlyhunt.com/submit',
      hosts: ['earlyhunt.com'],
      pricing: 'Free + Paid',
      entryStage: 'wizard',
      notes: '优先使用 Google 登录；选择无需徽章的 Nofollow Launch，并逐页填写资料和素材。站内 AI 提取不稳定，不作为主流程。',
    },
    {
      id: 'twelve_tools',
      name: 'Twelve Tools',
      submitUrl: 'https://twelve.tools/submit-your-tool',
      hosts: ['twelve.tools'],
      pricing: 'Free + Paid',
      entryStage: 'full_form',
      blocker: '免费方案要求在产品官网添加 Twelve Tools 的反向链接；插件不会修改产品官网。',
      notes: '直接打开已经核实的免费提交表单，不进入 Stripe 付款。',
    },
    {
      id: 'hot100',
      name: 'Hot100.ai',
      submitUrl: 'https://www.hot100.ai/submit',
      hosts: ['hot100.ai'],
      pricing: 'Free',
      entryStage: 'full_form',
      notes: 'Google 登录已验证；单页表单包含提交者身份、标题、网址、摘要、技术栈、缩略图、阶段和 Maker Links。',
    },
    {
      id: 'fazier',
      name: 'Fazier',
      submitUrl: 'https://fazier.com/submit',
      hosts: ['fazier.com'],
      pricing: 'Free + Paid',
      entryStage: 'plan_gate',
      blocker: '免费方案要求在产品官网或页脚长期放置 Fazier 徽章；Google 弹窗登录在本次验证中未稳定回到提交页。',
      notes: '插件不会自动确认官网徽章或进入付费套餐。',
    },
    {
      id: 'dang_ai',
      name: 'Dang AI',
      submitUrl: 'https://dang.ai/login?next=%2Fpricing',
      hosts: ['dang.ai'],
      pricing: 'Free',
      entryStage: 'login_gate',
      blocker: '只提供邮件安全链接登录，没有 Google 登录入口。',
      notes: '需要用户完成邮箱魔法链接后再继续。',
    },
    {
      id: 'findly_tools',
      name: 'Findly.tools',
      submitUrl: 'https://findly.tools/submit',
      hosts: ['findly.tools'],
      pricing: 'Free + Paid',
      entryStage: 'full_form',
      blocker: '免费方案要求在产品官网放置 Findly 徽章；无徽章方案为一次性付费。',
      notes: 'Google 登录已验证；表单包含名称、网址、分类、Logo、App Image、促销与出售开关和套餐。插件按 placeholder 与祖先标签映射名称/网址，并处理自定义分类下拉。',
    },
    {
      id: 'saashub',
      name: 'SaaSHub',
      submitUrl: 'https://www.saashub.com/',
      hosts: ['saashub.com'],
      pricing: 'Free',
      entryStage: 'bot_gate',
      blocker: '当前访问先进入反机器人检查，无法稳定读取提交表单。',
      notes: '实测为 Cloudflare 安全验证。插件立即通知用户接管并保留页面，验证通过后可继续录制。',
    },
    {
      id: 'betalist',
      name: 'BetaList',
      submitUrl: 'https://betalist.com/submit',
      hosts: ['betalist.com'],
      pricing: 'Free',
      entryStage: 'login_gate',
      blocker: '只提供 X、邮箱密码或邮箱魔法链接登录，没有 Google 登录入口。',
      notes: '用户登录后可继续录制提交表单。',
    },
    {
      id: 'tinylaunch',
      name: 'TinyLaunch',
      submitUrl: 'https://www.tinylaunch.com/',
      hosts: ['tinylaunch.com'],
      pricing: 'Free + Paid',
      entryStage: 'profile_gate',
      blocker: '首次 Google 登录后必须先完成并保存 Maker Profile，才能进入产品提交。',
      notes: 'Google 登录、Maker Profile 和产品表单已实测。插件可用用户资料自动填写首次 Profile，并提醒用户确认保存；产品表单包含名称、Tagline、Logo、最多 3 张图片、官网、富文本介绍、分类和反重复投票承诺，停在 Create Startup 前。',
    },
    {
      id: 'foundrlist',
      name: 'FoundrList',
      submitUrl: 'https://www.foundrlist.com/submit',
      hosts: ['foundrlist.com'],
      pricing: 'Free',
      entryStage: 'url_autofill',
      notes: 'Google 登录与 URL AI 预填均已验证；可抓取名称、Tagline、描述、分类、Logo 和封面，再补社交与 Demo。',
    },
    {
      id: 'open_launch',
      name: 'Open Launch',
      submitUrl: 'https://open-launch.com/projects/submit',
      hosts: ['open-launch.com'],
      pricing: 'Free',
      entryStage: 'wizard',
      notes: 'Google 登录已验证；四步流程为 Project Info、Details、Launch Date、Review，首屏包含富文本、Logo 和可选产品图。',
    },
    {
      id: 'microlaunch',
      name: 'MicroLaunch',
      submitUrl: 'https://microlaunch.net/',
      hosts: ['microlaunch.net'],
      pricing: 'Free',
      entryStage: 'dynamic_launch_gate',
      blocker: 'Google 登录成功，但 Launch 按钮未稳定暴露可识别的提交表单或固定提交 URL。',
      notes: 'Launch 是客户端动态入口；插件保留现场并通知用户接管，入口展开后从当前页面继续录制。',
    },
    {
      id: 'tiny_startups',
      name: 'Tiny Startups',
      submitUrl: 'https://www.tinystartups.com/submit',
      hosts: ['tinystartups.com'],
      pricing: 'Free',
      entryStage: 'login_then_form',
      notes: '提交入口稳定；未登录时先显示 Sign in to continue，登录完成后回到同一提交地址继续预填。',
    },
    {
      id: 'devhunt',
      name: 'DevHunt',
      submitUrl: 'https://devhunt.org/login',
      hosts: ['devhunt.org'],
      pricing: 'Paid',
      entryStage: 'login_then_form',
      notes: 'Google 登录与首次 Profile 已实测；表单包含 Logo、名称、Slogan、官网、GitHub、介绍、定价、分类、Demo 和媒体。当前可选 Launch Week 为 $49，插件必须停在付费或最终创建前。',
    },
    {
      id: 'super_launch',
      name: 'Super Launch',
      submitUrl: 'https://www.superlaun.ch/dashboard/submit',
      hosts: ['superlaun.ch', 'accounts.superlaun.ch'],
      pricing: 'Free',
      entryStage: 'login_then_form',
      notes: 'Clerk 登录页支持 Google；新账号需要走 Sign up。若 OAuth 回调未建立 External Account，提醒用户接管后再返回 dashboard/submit。',
    },
    {
      id: 'alternative_me',
      name: 'Alternative.me',
      submitUrl: 'https://alternative.me/how-to/submit-software/',
      hosts: ['alternative.me'],
      pricing: 'Free',
      entryStage: 'account_gate',
      blocker: '账号注册只支持显示名称、邮箱和密码，没有 Google 登录。',
      notes: '插件先打开官方 Submit a Software 指引；用户登录后再进入站内新增软件流程。',
    },
    {
      id: 'micro_saas_examples',
      name: 'Micro SaaS Examples',
      submitUrl: 'https://www.microsaasexamples.com/submit',
      hosts: ['microsaasexamples.com'],
      pricing: 'Free',
      entryStage: 'full_form',
      notes: '无需登录的单页表单；支持名称、URL、短描述、Logo、1200x630 缩略图、详细介绍、分类和联系邮箱，停在 Submit for review 前。',
    },
    {
      id: 'future_tools',
      name: 'Future Tools',
      submitUrl: 'https://futuretools.io/submit-a-tool',
      hosts: ['futuretools.io'],
      pricing: 'Free',
      entryStage: 'full_form',
      notes: '无需登录的单页表单；填写提交人姓名、工具名、URL、简介、分类、价格类型和邮箱，停在 Turnstile 与 Submit Tool 前。',
    },
    {
      id: 'llm_relevance',
      name: 'LLM Relevance',
      submitUrl: 'https://www.llmrelevance.com/submit',
      hosts: ['llmrelevance.com'],
      pricing: 'Free',
      entryStage: 'full_form',
      notes: '无需登录的单页表单；填写工具名、URL、分类、定价、可选 YouTube、创始人姓名和邮箱，停在 Submit Tool for Review 前。',
    },
    {
      id: 'made_with_bolt',
      name: 'Made with Bolt',
      submitUrl: 'https://madewithbolt.com/submit-project',
      hosts: ['madewithbolt.com'],
      pricing: 'Free',
      entryStage: 'full_form',
      blocker: '只接受使用 Bolt 构建的项目。',
      notes: '无需登录的单页表单；填写标题、邮箱、短描述、完整描述、网址和社交账号，停在 Submit Project 前。',
    },
    {
      id: 'made_with_lovable',
      name: 'Made with Lovable',
      submitUrl: 'https://madewithlovable.com/submit-project',
      hosts: ['madewithlovable.com'],
      pricing: 'Free + Paid',
      entryStage: 'full_form',
      blocker: '只接受使用 Lovable 构建的项目；最终提交受 reCAPTCHA 保护。',
      notes: '无需登录的单页表单；填写标题、邮箱、短描述、完整描述、网址和社交账号，默认保留免费方案并停在最终提交前。',
    },
    {
      id: 'hunt0',
      name: 'HUNT0',
      submitUrl: 'https://hunt0.com/submit',
      hosts: ['hunt0.com'],
      pricing: 'Free',
      entryStage: 'full_form_then_login',
      notes: '公开长表单支持产品资料、Markdown、Logo、图库、分类、标签、日期和社交链接；使用 Launch Kit 内存素材并停在 Sign in to submit 前。',
    },
    {
      id: 'saasgrow',
      name: 'SaaSGrow',
      submitUrl: 'https://saasgrow.app/submit',
      hosts: ['saasgrow.app'],
      pricing: 'Free',
      entryStage: 'google_login_then_form',
      notes: '优先 Google 登录；填写 URL、名称、分类、短描述和 Logo URL，停在 Submit SaaS 前。',
    },
    {
      id: 'acid_tools',
      name: 'Acid Tools',
      submitUrl: 'https://acidtools.com/submit',
      hosts: ['acidtools.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_badge_wizard',
      blocker: '免费方案要求在产品官网长期放置 Acid Tools 徽章；付费方案会跳转到 Dodo Payments。',
      notes: 'Google 登录与 Website、Badge、Details 阶段已核实；Details 支持名称、分类、定价、简介、详情、截图和图标，插件停在徽章、付款或 Submit for Review 前。',
    },
    {
      id: 'rank_in_public',
      name: 'RankInPublic',
      submitUrl: 'https://rankinpublic.xyz/launch',
      hosts: ['rankinpublic.xyz'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_wizard',
      notes: 'Google 登录后依次填写网址、名称、短描述、长描述，使用站内自动截图并选择至少三个标签；停在 Select Free 或 Select Premium $29 前。',
    },
    {
      id: 'startups_fm',
      name: 'Startups.fm',
      submitUrl: 'https://startups.fm/submit',
      hosts: ['startups.fm'],
      pricing: 'Free + Paid',
      entryStage: 'details_then_plan',
      blocker: '免费方案要求在产品官网持续放置 Startups.fm 徽章；免徽章快速通道为 £49。',
      notes: '无需登录；填写产品资料、Logo、横版图片和提交者信息，素材使用 Launch Kit 内存文件，停在免费徽章确认或付费前。',
    },
    {
      id: 'startup_fame',
      name: 'Startup Fame',
      submitUrl: 'https://startupfa.me/login',
      hosts: ['startupfa.me'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_dynamic_submit',
      notes: '从官方登录入口优先使用 Google；登录后动态发现 Submit，不使用已失效的 /submit。',
    },
    {
      id: 'turbo0',
      name: 'Turbo0',
      submitUrl: 'https://turbo0.com/submit',
      hosts: ['turbo0.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: 'Google 登录回调保留 /submit，登录完成后继续表单。',
    },
    {
      id: 'alternative_to',
      name: 'AlternativeTo',
      submitUrl: 'https://alternativeto.net/login/',
      hosts: ['alternativeto.net'],
      pricing: 'Free',
      entryStage: 'google_login_then_dynamic_submit',
      blocker: '新账号必须注册满 7 天才能提交新应用。',
      notes: 'GitHub 登录后已实测 /manage-item/ 真实表单：名称、短/长介绍、官网、定价、开源、标签、功能、平台、社交、Icon、截图、视频和备注。插件停在 Submit the application 前；新账号需等待 7 天。',
    },
    {
      id: 'toolpilot',
      name: 'ToolPilot',
      submitUrl: 'https://form.jotform.com/231772738321053',
      hosts: ['toolpilot.ai', 'form.jotform.com'],
      pricing: 'Free + Paid',
      entryStage: 'external_full_form',
      blocker: '免费方案要求产品官网提供反向链接。',
      notes: '公开 Jotform；支持产品、创始人、分类、功能与 500×500 Logo，Logo 必须由 Launch Kit 内存素材注入，停在 Submit 前。',
    },
    {
      id: 'peerlist',
      name: 'Peerlist Launchpad',
      submitUrl: 'https://peerlist.io/launchpad',
      hosts: ['peerlist.io'],
      pricing: 'Free',
      entryStage: 'profile_login_then_dynamic_submit',
      blocker: '首次 Profile 可自动填写，但 Launch 前仍可能要求完成 40% 资料并通过 Peerlist Verification。',
      notes: 'Google 登录、首次 Profile、Verification、Launchpad 与下周排期入口已实测。项目表单支持 URL AI 自动填充、名称、官网、Tagline、最多 3 个分类、最多 10 个技术栈、协作者、开源标记、5000 字介绍、500×500 Logo、最多 4 张 1200×630 封面和 Demo 视频；停在 Save Project 前。',
    },
    {
      id: 'launch_igniter',
      name: 'LaunchIgniter',
      submitUrl: 'https://launchigniter.com/submit',
      hosts: ['launchigniter.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: 'Google 登录和首次 Profile 已实测。表单包含 ProductHunt/Peerlist 快速导入、名称、Tagline、介绍、官网、Logo、最多 4 张截图、最多 3 个分类、Demo、开源与 vibe-coded 选项；停在 Submit Product 前。',
    },
    {
      id: 'neeed_directory',
      name: 'Neeed Directory',
      submitUrl: 'https://neeed.directory/login?redirect=/submit',
      hosts: ['neeed.directory'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: '已登录表单支持官网 Prefill，自动抓取名称、Punchline、介绍、官网、分类和 Logo；另需 256×256 Logo、1280×720 Cover，下一步为 Launch plan，停在最终提交前。',
    },
    {
      id: 'startup_fast',
      name: 'StartupFast',
      submitUrl: 'https://www.startupfa.st/projects/submit',
      hosts: ['startupfa.st'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: 'Google 登录已实测。五阶段为 Startup、Project Info、Details、Launch Date、Review；可选择个人 Profile，项目信息支持官网 Auto-fill、名称、短介绍、必填 Logo 与可选 Cover，停在 Review 的最终提交前。',
    },
    {
      id: 'sideprojectors',
      name: 'SideProjectors',
      submitUrl: 'https://www.sideprojectors.com/submit/type',
      hosts: ['sideprojectors.com'],
      pricing: 'Free',
      entryStage: 'google_login_then_wizard',
      notes: 'Google 登录和 Showcase 入口已实测。支持官网自动抓取、Product Hunt/GitHub/GitLab 导入或从零填写；广告遮挡时提醒用户接管，且始终停在最终提交前。',
    },
    {
      id: 'ai_tools_inc',
      name: 'AI Tools Inc',
      submitUrl: 'https://loxr142exnq.typeform.com/to/RB6ZnEf2',
      hosts: ['aitools.inc', 'loxr142exnq.typeform.com'],
      pricing: 'Free + Paid',
      entryStage: 'external_typeform',
      notes: '公开顺序式 Typeform；保持免费分支，逐题填写并停在最终 Submit 前。',
    },
    {
      id: 'nxgn_tools',
      name: 'NXGN Tools',
      submitUrl: 'https://www.nxgntools.com/',
      hosts: ['nxgntools.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_dynamic_submit',
      notes: '从首页 Launch Tool 动态入口进入登录和免费发布，不进入 premium_launch。',
    },
    {
      id: 'launchllama_tools',
      name: 'LaunchLlama Tools',
      submitUrl: 'https://tools.launchllama.co/submit',
      hosts: ['tools.launchllama.co', 'launchllama.co'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: '登录回调保留 /submit，完成登录后继续产品表单。',
    },
    {
      id: 'indie_deals',
      name: 'Indie Deals',
      submitUrl: 'https://indie.deals/submit',
      hosts: ['indie.deals'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: '优先 Google 登录并返回 /submit；不进入 PRO 付款。',
    },
    {
      id: 'startupbase',
      name: 'StartupBase',
      submitUrl: 'https://startupbase.io/submit',
      hosts: ['startupbase.io'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: 'Google 登录、首次 Profile 和五区段草稿已实测。General、Media、Makers、Extras、Launch Checklist 支持名称、Tagline、官网、描述、标签、Logo、最多 8 张截图、视频、Maker、优惠、定价和首评；停在 Schedule Your Launch 前。',
    },
    {
      id: 'unitelist',
      name: 'UniteList',
      submitUrl: 'https://unitelist.com/get-started',
      hosts: ['unitelist.com'],
      pricing: 'Free + Paid',
      entryStage: 'manual_only',
      blocker: '免费方案要求在产品官网添加指向专属 listing URL 的 do-follow 徽章并通过 Verify Badge。',
      notes: '判定为不能全自动化：必须先修改产品官网并验证 do-follow 徽章；付费方案不自动进入。',
    },
    {
      id: 'fridayhunt',
      name: 'FridayHunt',
      submitUrl: 'https://fridayhunt.com/projects/submit',
      hosts: ['fridayhunt.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: 'Google 登录前需勾选条款。四步流程首屏包含名称、域名、50–160 字短介绍、Logo、16:9 产品图和 200–4500 字富文本介绍；停在最终发布前，不使用邮件 magic link。',
    },
    {
      id: 'firsto',
      name: 'Firsto',
      submitUrl: 'https://firsto.co/projects/submit',
      hosts: ['firsto.co'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: 'Google 登录与官网 AI 草稿已实测。四阶段为 Project Info、Project Details、Launch Settings、Confirmation；自动生成名称、160 字短介绍、Logo、150+ 字 Markdown 长介绍与分类，Cover 为必填。当前免费档未来 180 天无空位，插件不得自动进入付费或最终确认。',
    },
    {
      id: 'saas_hunt_best',
      name: 'SaaSHunt',
      submitUrl: 'https://saashunt.best/projects/submit',
      hosts: ['saashunt.best'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      blocker: '免费流程可能要求产品官网徽章。',
      notes: '优先 Google 登录，填写后停在徽章、付款或最终提交前。',
    },
    {
      id: 'appalist',
      name: 'AppaList',
      submitUrl: 'https://appalist.com/get-started',
      hosts: ['appalist.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: '从 get-started 选择安全免费分支并使用 Google 登录。',
    },
    {
      id: 'weliketools',
      name: 'WeLikeTools',
      submitUrl: 'https://weliketools.com/get-started',
      hosts: ['weliketools.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: '从 get-started 使用 Google 登录后继续工具表单。',
    },
    {
      id: 'startup_trusted',
      name: 'StartupTrusted',
      submitUrl: 'https://startuptrusted.com/submit',
      hosts: ['startuptrusted.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_form',
      notes: 'Google 登录 callbackUrl 保留 /submit。',
    },
    {
      id: 'promote_project',
      name: 'PromoteProject',
      submitUrl: 'https://www.promoteproject.com/',
      hosts: ['promoteproject.com'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_modal_then_form',
      notes: '从首页 Submit startup 打开登录弹窗，优先 Google 登录后继续。',
    },
    {
      id: 'saas_bison',
      name: 'SaaSBison',
      submitUrl: 'https://saasbison.com/submit',
      hosts: ['saasbison.com'],
      pricing: 'Free + Paid',
      entryStage: 'badge_then_form',
      blocker: '免费方案要求产品官网永久反向链接；Premium 为 $9.99。',
      notes: '停在徽章验证或付款边界；验证完成后继续 Details 和 Publish。',
    },
    {
      id: 'proofstories',
      name: 'ProofStories',
      submitUrl: 'https://proofstories.io/submit/',
      hosts: ['proofstories.io'],
      pricing: 'Free',
      entryStage: 'google_login_then_form',
      notes: 'Google 登录后继续故事/产品提交，可能需要收入证明；停在最终提交前。',
    },
    {
      id: 'find_your_saas',
      name: 'FindYourSaaS',
      submitUrl: 'https://findyoursaas.com/onboard',
      hosts: ['findyoursaas.com'],
      pricing: 'Free + Paid',
      entryStage: 'login_then_dynamic_form',
      notes: '从 onboard 的免费 Standard listing 进入登录，登录后动态寻找表单。',
    },
    {
      id: 'toolfolio',
      name: 'Toolfolio',
      submitUrl: 'https://toolfolio.com/boosted-listing',
      hosts: ['toolfolio.io', 'toolfolio.com'],
      pricing: 'Paid',
      entryStage: 'paid_package_gate',
      blocker: '当前 Submit tool 只进入付费 boosted-listing 套餐构建器。',
      notes: '插件停在套餐或付款前，不自动进入结算。',
    },
    {
      id: 'indiehub',
      name: 'IndieHub',
      submitUrl: 'https://indiehub.best/submit',
      hosts: ['indiehub.best'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_wizard',
      notes: 'Google 登录后依次执行 Details、Payment、Publish；图片使用 Launch Kit 内存素材并停在付款或最终提交前。',
    },
    {
      id: 'dodo_directory',
      name: 'DodoDirectory',
      submitUrl: 'https://dododirectory.com/submit',
      hosts: ['dododirectory.com'],
      pricing: 'Free + Paid',
      entryStage: 'badge_then_form',
      blocker: '免费方案要求产品官网永久徽章。',
      notes: '三阶段为 Submission Type、Details、Publish；停在徽章验证或付款前。',
    },
    {
      id: 'build_voyage',
      name: 'BuildVoyage',
      submitUrl: 'https://buildvoyage.com/submit',
      hosts: ['buildvoyage.com'],
      pricing: 'Free',
      entryStage: 'wizard',
      notes: '公开两阶段 Product Information 与 Tech Stack，使用内存 Logo，停在最终 review/submit 前。',
    },
    {
      id: 'sumodir',
      name: 'SumoDir',
      submitUrl: 'https://sumodir.com/submit',
      hosts: ['sumodir.com'],
      pricing: 'Free + Paid',
      entryStage: 'badge_then_form',
      blocker: '免费方案要求产品官网反向链接；付费方案由 Polar 结算。',
      notes: '三阶段为 Submission Type、Details、Publish；停在徽章或付款边界。',
    },
    {
      id: 'confetti_saas',
      name: 'ConfettiSaaS',
      submitUrl: 'https://confettisaas.com/submit',
      hosts: ['confettisaas.com', 'tally.so'],
      pricing: 'Free',
      entryStage: 'external_wizard',
      notes: '两页嵌入式 Tally；使用 Launch Kit 内存图片，逐页填写并停在最终 Submit 前。',
    },
    {
      id: 'shipyard_hq',
      name: 'Shipyard HQ',
      submitUrl: 'https://shipyardhq.dev/member/products/add',
      hosts: ['shipyardhq.dev', 'accounts.shipyardhq.dev'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_profile_then_form',
      blocker: '首次账号需要用户确认姓氏并接受服务条款。',
      notes: '完成首次资料后自动回到产品新增页继续。',
    },
    {
      id: 'resource_fyi',
      name: 'Resource.fyi',
      submitUrl: 'https://resource.fyi/',
      hosts: ['resource.fyi'],
      pricing: 'Free',
      entryStage: 'dynamic_login_then_form',
      notes: '通过 Submit Resource 客户端按钮进入登录/表单，使用录制流程而非猜测 URL。',
    },
    {
      id: 'stellar_launch',
      name: 'Stellar Launch',
      submitUrl: 'https://www.stellarlaunch.org/projects/submit',
      hosts: ['stellarlaunch.org'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_wizard',
      notes: 'Google 登录已验证；四步为 Project Info、Details、Launch Date、Review。首屏名称、网址、Tagline 和富文本介绍已实测自动填写，Logo 为必填，停在最终提交前。',
    },
    {
      id: 'indie_hacker_stacks',
      name: 'IndieHackerStacks',
      submitUrl: 'https://indiehackerstacks.com/',
      hosts: ['indiehackerstacks.com'],
      pricing: 'Free + Paid',
      entryStage: 'dynamic_login_then_wizard',
      blocker: 'Add your product stack 是客户端动态入口，未稳定暴露登录或表单。',
      notes: '插件点击动态入口；若页面未切换则通知用户接管，并从当前页继续产品及技术栈录制。',
    },
    {
      id: 'product_launchpad',
      name: 'ProductLaunchpad',
      submitUrl: 'https://productlaunchpad.app/submit',
      hosts: ['productlaunchpad.app'],
      pricing: 'Free + Paid',
      entryStage: 'email_login_then_form',
      blocker: '只支持邮箱登录，需用户完成邮件验证。',
      notes: '验证后通过 next=/submit 自动恢复。',
    },
    {
      id: 'launchy',
      name: 'Launchy',
      submitUrl: 'https://launchy.tools/submit',
      hosts: ['launchy.tools'],
      pricing: 'Free + Paid',
      entryStage: 'google_login_then_wizard',
      blocker: '1280×720 缩略图为必填；缺少或上传失败时需要用户接管。',
      notes: 'Google 登录已验证；名称、Tagline、富文本介绍和网址已实测自动填写，上传缩略图后逐页执行并停在最终提交前。',
    },
    {
      id: 'sourceforge',
      name: 'SourceForge',
      submitUrl: 'https://sourceforge.net/software/vendors/',
      hosts: ['sourceforge.net'],
      pricing: 'Free',
      entryStage: 'manual_only',
      blocker: '需要独立 SourceForge Vendor 账号，且当前入口主要引导销售套餐；没有可稳定自动登录的 Google 流程。',
      notes: '判定为不能稳定自动化；保留人工 Add a Product，插件不再反复打开页面。',
    },
    {
      id: 'g2',
      name: 'G2',
      submitUrl: 'https://www.g2.com/add_product_requests/new',
      hosts: ['g2.com'],
      pricing: 'Free',
      entryStage: 'google_login_then_form',
      blocker: 'Google 登录未显示账号选择器时，需要用户输入邮箱完成首次登录。',
      notes: 'Google 登录已完成；流程包含产品类型、GA/Beta、资格确认、官网验证和公司资料，停在最终申请前。',
    },
    {
      id: 'product_hunt',
      name: 'Product Hunt',
      submitUrl: 'https://www.producthunt.com/',
      hosts: ['producthunt.com'],
      pricing: 'Free',
      entryStage: 'account_gate',
      blocker: '当前仅提供 LinkedIn、GitHub 和 X 登录；首次登录后还需邮箱确认。',
      notes: '账号登录已完成；邮箱确认后从 /posts/new 继续 Launch 流程，停在最终发布前。',
    },
    {
      id: 'capterra',
      name: 'Capterra',
      submitUrl: 'https://www.capterra.com/vendors/',
      hosts: ['capterra.com'],
      pricing: 'Free',
      entryStage: 'manual_only',
      blocker: 'Vendor 入口受 Cloudflare 与独立供应商流程影响，未获得稳定可重放表单。',
      notes: '判定为不能稳定自动化；保留人工供应商申请，插件不再反复打开页面。',
    },
    {
      id: 'submit_ai_tools',
      name: 'Submit AI Tools',
      submitUrl: 'https://submitaitools.org/submit-your-ai-tool/',
      hosts: ['submitaitools.org'],
      pricing: 'Paid',
      entryStage: 'paid_package_gate',
      blocker: '人工验证通过后仅显示付费提交，Basic 当前为 $19 lifetime。',
      notes: '标记为需要付费；插件不再填写或进入付款。',
    },
    {
      id: 'software_world',
      name: 'SoftwareWorld',
      submitUrl: 'https://www.softwareworld.co/register/',
      hosts: ['softwareworld.co'],
      pricing: 'Paid',
      entryStage: 'paid_package_gate',
      blocker: '新软件发布需要一次性 $99 approval fee；注册页另有 reCAPTCHA。',
      notes: '标记为需要付费；已有 SoftwareWorld Profile 的认领可能免费，但新产品不继续自动录制。',
    },
    {
      id: 'startup_stash',
      name: 'Startup Stash',
      submitUrl: 'https://startupstash.com/add-listing/',
      hosts: ['startupstash.com'],
      pricing: 'Free + Paid',
      entryStage: 'manual_only',
      blocker: '11 步 Typeform 嵌入表单会动态重排问题与输入焦点，无法稳定重放。',
      notes: '判定为不能稳定自动化；保留人工 Typeform 提交，避免错误覆盖用户资料。',
    },
    {
      id: 'magicbox_tools',
      name: 'MagicBox.tools',
      submitUrl: 'https://magicbox.tools/submit',
      hosts: ['magicbox.tools'],
      pricing: 'Paid',
      entryStage: 'paid_package_gate',
      blocker: '填写名称、官网和邮箱后只提供付费方案，Basic 当前为 $15.9 one time。',
      notes: '标记为需要付费；插件不进入套餐或结算。',
    },
  ];

  const baseRequirements = [
    { key: 'productName', resolution: 'user', required: true },
    { key: 'productUrl', resolution: 'user', required: true },
    { key: 'tagline', resolution: 'ai', required: true },
    {
      key: 'shortDescription',
      resolution: 'ai',
      required: true,
      minLength: 20,
    },
  ];
  const longDescriptionDirectories = new Set([
    'aura_plus_plus',
    'openhunts',
    'earlyhunt',
    'tinylaunch',
    'open_launch',
    'micro_saas_examples',
    'made_with_bolt',
    'made_with_lovable',
    'hunt0',
    'acid_tools',
    'rank_in_public',
    'alternative_to',
    'toolpilot',
    'peerlist',
    'launch_igniter',
    'neeed_directory',
    'startup_fast',
    'startupbase',
    'fridayhunt',
    'firsto',
    'stellar_launch',
    'launchy',
  ]);
  const categoryDirectories = new Set([
    'aura_plus_plus',
    'openhunts',
    'earlyhunt',
    'twelve_tools',
    'hot100',
    'findly_tools',
    'tinylaunch',
    'foundrlist',
    'open_launch',
    'micro_saas_examples',
    'future_tools',
    'llm_relevance',
    'hunt0',
    'acid_tools',
    'alternative_to',
    'toolpilot',
    'peerlist',
    'launch_igniter',
    'neeed_directory',
    'startup_fast',
    'startupbase',
    'fridayhunt',
    'firsto',
    'build_voyage',
    'stellar_launch',
  ]);
  const pricingDirectories = new Set([
    'openhunts',
    'hot100',
    'findly_tools',
    'future_tools',
    'llm_relevance',
    'acid_tools',
    'alternative_to',
    'toolpilot',
    'startupbase',
  ]);
  const founderNameDirectories = new Set([
    'hot100',
    'future_tools',
    'llm_relevance',
    'toolpilot',
    'startups_fm',
  ]);
  const founderEmailDirectories = new Set([
    'twelve_tools',
    'hot100',
    'future_tools',
    'llm_relevance',
    'made_with_bolt',
    'made_with_lovable',
    'micro_saas_examples',
    'toolpilot',
    'startups_fm',
    'magicbox_tools',
  ]);
  const requiredLogoDirectories = new Set([
    'aura_plus_plus',
    'openhunts',
    'earlyhunt',
    'twelve_tools',
    'hot100',
    'findly_tools',
    'tinylaunch',
    'open_launch',
    'micro_saas_examples',
    'hunt0',
    'acid_tools',
    'startups_fm',
    'alternative_to',
    'toolpilot',
    'peerlist',
    'launch_igniter',
    'neeed_directory',
    'startup_fast',
    'startupbase',
    'fridayhunt',
    'firsto',
    'build_voyage',
    'stellar_launch',
  ]);
  const requiredScreenshotDirectories = new Set([
    'aura_plus_plus',
    'openhunts',
    'findly_tools',
    'micro_saas_examples',
    'acid_tools',
    'startups_fm',
    'peerlist',
    'neeed_directory',
    'fridayhunt',
    'firsto',
    'launchy',
  ]);
  const assetSpecs = {
    aura_plus_plus: {
      logo: { width: 512, height: 512, type: 'image/png' },
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.86,
      },
    },
    micro_saas_examples: {
      logo: {
        width: 256,
        height: 256,
        type: 'image/png',
        maxBytes: 1000000,
      },
      screenshot: {
        width: 1200,
        height: 630,
        type: 'image/jpeg',
        quality: 0.88,
        maxBytes: 4000000,
      },
    },
    toolpilot: {
      logo: {
        width: 500,
        height: 500,
        type: 'image/jpeg',
        quality: 0.9,
      },
    },
    peerlist: {
      logo: { width: 500, height: 500, type: 'image/png' },
      screenshot: {
        width: 1200,
        height: 630,
        type: 'image/jpeg',
        quality: 0.88,
        maxCount: 4,
      },
    },
    launch_igniter: {
      logo: { width: 512, height: 512, type: 'image/png' },
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.86,
        maxCount: 4,
      },
    },
    launchllama_tools: {
      logo: { width: 512, height: 512, type: 'image/png' },
      screenshot: {
        width: 1200,
        height: 630,
        type: 'image/jpeg',
        quality: 0.88,
      },
    },
    neeed_directory: {
      logo: { width: 256, height: 256, type: 'image/png' },
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.88,
      },
    },
    indiehub: {
      logo: { width: 512, height: 512, type: 'image/png' },
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.86,
      },
    },
    stellar_launch: {
      logo: { width: 512, height: 512, type: 'image/png' },
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.86,
      },
    },
    fridayhunt: {
      logo: { width: 512, height: 512, type: 'image/png' },
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.86,
      },
    },
    firsto: {
      logo: { width: 512, height: 512, type: 'image/png' },
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.86,
      },
    },
    launchy: {
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.88,
      },
    },
    confetti_saas: {
      screenshot: {
        width: 1280,
        height: 720,
        type: 'image/jpeg',
        quality: 0.88,
      },
    },
  };
  const autoSubmitOptIn = new Set([
    'micro_saas_examples',
    'llm_relevance',
    'build_voyage',
  ]);
  const backlinkDirectories = new Set([
    'toolfio',
    'twelve_tools',
    'fazier',
    'findly_tools',
    'acid_tools',
    'startups_fm',
    'toolpilot',
    'unitelist',
    'saas_hunt_best',
    'saas_bison',
    'dodo_directory',
    'sumodir',
  ]);
  const extraRequirements = {
    hot100: [
      ['techStack', 'ai'],
      ['productStage', 'user'],
      ['twitterUrl', 'user'],
      ['linkedinUrl', 'user'],
      ['githubUrl', 'user'],
    ],
    foundrlist: [
      ['twitterUrl', 'user'],
      ['linkedinUrl', 'user'],
      ['demoUrl', 'user'],
    ],
    devhunt: [
      ['githubUrl', 'user'],
      ['demoUrl', 'user'],
    ],
    llm_relevance: [['youtubeUrl', 'user']],
    made_with_bolt: [['twitterUrl', 'user']],
    made_with_lovable: [['twitterUrl', 'user']],
    hunt0: [
      ['twitterUrl', 'user'],
      ['linkedinUrl', 'user'],
      ['githubUrl', 'user'],
      ['launchDate', 'user'],
    ],
    alternative_to: [
      ['featureHighlights', 'ai'],
      ['supportedPlatforms', 'ai'],
      ['twitterUrl', 'user'],
      ['linkedinUrl', 'user'],
      ['githubUrl', 'user'],
      ['youtubeUrl', 'user'],
      ['demoUrl', 'user'],
    ],
    toolpilot: [
      ['companyName', 'user'],
      ['featureHighlights', 'ai'],
      ['supportedPlatforms', 'ai'],
      ['integrations', 'ai'],
      ['apiAvailability', 'user'],
      ['communityAvailability', 'user'],
      ['twitterUrl', 'user'],
      ['linkedinUrl', 'user'],
    ],
    peerlist: [
      ['techStack', 'ai'],
      ['githubUrl', 'user'],
      ['demoUrl', 'user'],
    ],
    launch_igniter: [['demoUrl', 'user']],
    startupbase: [['demoUrl', 'user']],
    build_voyage: [['techStack', 'ai']],
    product_launchpad: [['techStack', 'ai']],
  };

  function directoryRequirements(directory) {
    const result = baseRequirements.map((item) => ({ ...item }));
    const add = (key, resolution, options = {}) => {
      if (result.some((item) => item.key === key)) return;
      result.push({
        key,
        resolution,
        required: options.required !== false,
        ...(options.minLength ? { minLength: options.minLength } : {}),
        ...(options.detail ? { detail: options.detail } : {}),
        ...(options.assetSpec ? { assetSpec: options.assetSpec } : {}),
      });
    };
    if (longDescriptionDirectories.has(directory.id)) {
      add('longDescription', 'ai', {
        minLength: directory.id === 'aura_plus_plus' ? 900 : 80,
        detail:
          directory.id === 'aura_plus_plus'
            ? '至少 200 词'
            : undefined,
      });
    }
    if (categoryDirectories.has(directory.id)) add('categories', 'ai');
    if (pricingDirectories.has(directory.id)) add('pricing', 'user');
    if (founderNameDirectories.has(directory.id)) add('founderName', 'user');
    if (founderEmailDirectories.has(directory.id)) add('founderEmail', 'user');
    if (requiredLogoDirectories.has(directory.id)) {
      add('logo', 'user', {
        assetSpec: assetSpecs[directory.id]?.logo,
      });
    }
    if (requiredScreenshotDirectories.has(directory.id)) {
      add('screenshots', 'user', {
        assetSpec: assetSpecs[directory.id]?.screenshot,
      });
    }
    if (backlinkDirectories.has(directory.id)) {
      add('backlinkUrl', 'user', {
        required: false,
        detail: '免费方案需要在产品官网添加反向链接或徽章',
      });
    }
    for (const [key, resolution] of extraRequirements[directory.id] || []) {
      add(key, resolution, { required: false });
    }
    return result;
  }

  for (const directory of directories) {
    directory.requirements = directoryRequirements(directory);
    directory.assetSpecs = assetSpecs[directory.id] || {};
    directory.requirementsConfidence =
      /bot_gate|account_gate|login_gate|dynamic|paid_package_gate/.test(
        directory.entryStage
      )
        ? 'partial'
        : 'verified';
    directory.submissionPolicy = autoSubmitOptIn.has(directory.id)
      ? 'auto_submit_opt_in'
      : 'prepare_only';
  }

  global.NowBuildDirectoryCatalog = {
    version: '0.9.14',
    directories,
    byId(id) {
      return directories.find((directory) => directory.id === id);
    },
    byHost(hostname) {
      return directories.find((directory) =>
        directory.hosts.some(
          (host) => hostname === host || hostname.endsWith(`.${host}`)
        )
      );
    },
  };
})(globalThis);
